### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'   what():  map::at

### ISSUE THREAD

**Issue by clbr** [MartinezTorres/marlin#9]
```
double prob[256] = { 0 };
Marlin *mine = Marlin_build_dictionary("mine", prob);
```

I think the same happens if one probability is 1 and the others 0, but this is the easiest reproducer.

**Comment by MartinezTorres** [comment]
I added a sanitizer for the histogram, so that it does not fail catastrophically on such a corner case, but there may be still many corner cases to be investigated.

**Comment by MartinezTorres** [comment]
I'll close this issue for now, but the entire front end of the library must be checked for corner case inputs.
